import type { Metadata } from "next";
import { dir } from "i18next";

import { languages } from "../i18n/settings";
import "../globals.css";

export interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const generateStaticParams = async () =>
  languages.map((lng) => ({ lng }));

export default async ({ children, params }: Readonly<LayoutProps>) => {
  const lang = (await params).lang;

  return (
    <html lang={lang} data-test={lang}>
      <body className={`antialiased`}>
        lang in layout: {lang}
        <div>{children}</div>
      </body>
    </html>
  );
};
